# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-22 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('path', models.FilePathField(max_length=30, verbose_name='项目路径')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目列表',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='hostname',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='主机名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='assets',
            field=models.ManyToManyField(to='asset.Asset', verbose_name='所在主机'),
        ),
    ]
