# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-16 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': '主机', 'verbose_name_plural': '主机列表'},
        ),
    ]
