# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-19 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190716_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='port',
            field=models.IntegerField(blank=True, default=22, verbose_name='端口'),
        ),
    ]
