# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-23 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190722_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='username',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='assets',
            field=models.ManyToManyField(related_name='projects', to='asset.Asset', verbose_name='所在主机'),
        ),
        migrations.AlterField(
            model_name='project',
            name='path',
            field=models.CharField(default='/data/xls/runtime', max_length=30, verbose_name='项目路径'),
        ),
    ]
