# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-29 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='host',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='主机ip'),
        ),
    ]
