# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-19 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('config_path', models.CharField(default='~/.jenkins', max_length=50, verbose_name='jenkins数据储存路径')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset', verbose_name='主机')),
            ],
            options={
                'verbose_name': 'jenkins配置',
                'verbose_name_plural': 'jenkins配置',
            },
        ),
    ]
