# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-17 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('jenkins_a', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenkinsconfig',
            name='created',
        ),
        migrations.RemoveField(
            model_name='jenkinsconfig',
            name='host',
        ),
        migrations.RemoveField(
            model_name='jenkinsconfig',
            name='ssh_secret_key',
        ),
        migrations.AddField(
            model_name='jenkinsconfig',
            name='asset',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='asset.Asset', verbose_name='主机'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jenkinsconfig',
            name='config_path',
            field=models.CharField(default='~/.jenkins', max_length=50, verbose_name='jenkins数据储存路径'),
        ),
        migrations.AddField(
            model_name='jenkinsconfig',
            name='password',
            field=models.CharField(default='', max_length=20, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jenkinsconfig',
            name='username',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
    ]
