# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-23 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_a', '0002_jenkinsconfig_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenkinsconfig',
            name='config_path',
            field=models.CharField(default='~/.jenkins', max_length=200, verbose_name='jenkins数据储存路径'),
        ),
    ]
